name: Release drafter

on: workflow_dispatch

permissions:
  contents: read

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        id: read_version
        run: |
          echo "version=$(cat version/VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo ${{ steps.read_version.outputs.version }}
      - uses: release-drafter/release-drafter@v6
        id: release
        with:
          version: ${{ steps.read_version.outputs.version }}
          name: v${{ steps.read_version.outputs.version }}
          tag: v${{ steps.read_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_amd64:
    runs-on: macos-13
    needs: draft_release
    name: Release amd64
    permissions:
      contents: write
      pull-requests: write
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.draft_release.outputs.tag_name }}
      CGO_ENABLED: 0
      PROJECT_PATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v4
    - name: Display GCC&&Make version
      run: |
        gcc --version
        make --version
    - name: darwin/amd64
      env: 
        BOS: darwin
        BARCH: amd64
      run: |
        cd $PROJECT_PATH
        ls
        make
        mv hev-socks5-tunnel hev-socks5-tunnel-x64
        chmod +x hev-socks5-tunnel-x64
        tar -zcvf "hev-socks5-tunnel-$BOS-$BARCH.tar.gz" hev-socks5-tunnel-x64 && rm -r hev-socks5-tunnel-x64
        gh release upload $TAG_NAME "./hev-socks5-tunnel-$BOS-$BARCH.tar.gz"

  build_arm64:
    runs-on: macos-14
    needs: draft_release
    name: Release arm64
    permissions:
      contents: write
      pull-requests: write
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.draft_release.outputs.tag_name }}
      CGO_ENABLED: 0
      PROJECT_PATH: ${{ github.workspace }}
    steps:
    - uses: actions/checkout@v4
    - name: Display GCC&&Make version
      run: |
        gcc --version
        make --version
    - name: darwin/arm64
      env: 
        BOS: darwin
        BARCH: arm64
      run: |
        cd $PROJECT_PATH
        make
        mv hev-socks5-tunnel hev-socks5-tunnel-arm
        chmod +x hev-socks5-tunnel-arm
        tar -zcvf "hev-socks5-tunnel-$BOS-$BARCH.tar.gz" hev-socks5-tunnel-arm && rm -r hev-socks5-tunnel-arm
        gh release upload $TAG_NAME "./hev-socks5-tunnel-$BOS-$BARCH.tar.gz"