name: "Build"

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Read version
        id: read_version
        run: |
          echo "version=$(cat version/VERSION | tr -d '[:space:]')" >> $GITHUB_OUTPUT
      - name: Print version
        run: |
          echo ${{ steps.read_version.outputs.version }}
      - uses: release-drafter/release-drafter@v6
        id: release
        with:
          version: ${{ steps.read_version.outputs.version }}
          name: v${{ steps.read_version.outputs.version }}
          tag: v${{ steps.read_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  macos:
    name: macOS
    runs-on: macos-14
    permissions:
      contents: write
      pull-requests: write
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_NAME: ${{ needs.draft_release.outputs.tag_name }}
      CGO_ENABLED: 0
      PROJECT_PATH: ${{ github.workspace }}
      BOS: darwin
      BARCH: uni
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Build cross
        run: |
          cd $PROJECT_PATH
          ./build-apple.sh
      - name: Upload Release
        run: |
          cd $PROJECT_PATH
          tar -zcvf "hev-socks5-tunnel-$BOS-$BARCH.tar.gz" HevSocks5Tunnel.xcframework
          gh release upload $TAG_NAME "./hev-socks5-tunnel-$BOS-$BARCH.tar.gz"
