name: "Build"

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  source:
    name: Source
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Gen Source
        run: |
          REV_ID=$(git rev-parse --short HEAD)
          mkdir -p hev-socks5-tunnel-${{ github.ref_name }}
          git ls-files --recurse-submodules | tar c -O -T- | tar x -C hev-socks5-tunnel-${{ github.ref_name }}
          echo ${REV_ID} > hev-socks5-tunnel-${{ github.ref_name }}/.rev-id
          tar cJf hev-socks5-tunnel-${{ github.ref_name }}.tar.xz hev-socks5-tunnel-${{ github.ref_name }}
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: hev-socks5-tunnel-${{ github.ref_name }}.tar.xz
          path: hev-socks5-tunnel-${{ github.ref_name }}.tar.xz
          if-no-files-found: error
          retention-days: 1
  macos:
    name: macOS
    runs-on: macos-14
    if: github.event_name != 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Build native
        run: |
          make
          make clean
      - name: Build cross
        run: |
          ./build-apple.sh
